/**
 * Real-world scam patterns (modeled on published Discord/Steam phishing campaigns)
 * and legitimate messages. The detector must flag every scam and none of the legit ones.
 * All scam domains here are examples of patterns; don't treat them as a blocklist.
 */

export const SCAM_MESSAGES: string[] = [
  // Discord homoglyphs and typos
  'free nitro https://dlscord.gift/abc123',
  'https://discorcl.com/nitro',
  'https://d1scord.com/gift',
  'https://disc0rd-nitro.com/claim',
  'https://dicsord.com/airdrop',
  'https://discrod.gift/xyz',
  'https://dicord.com/verify',
  'https://discordd.com/invite/abc',
  'https://dlscordapp.com/login',
  'https://dlscord.gg/partner',
  'https://dіscord.com/nitro',
  'https://discοrd.com/gift',
  'https://rnetamask.io/restore',
  'https://robIox.com/users/1/profile',
  // Brand name on a domain the brand doesn't own, plus bait
  'https://discord-gift.com free nitro for everyone',
  'https://discordnitro.store/claim',
  'https://discordapp.gift/xyz',
  'https://discord.gifts/abc',
  'https://discordc.gift/abc',
  'https://nitro-discord.xyz/',
  'https://discord-app.click/login',
  'https://discordgivenitro.com/',
  'https://free-nitro.discord-events.com/',
  'https://discord-airdrop.com/',
  'https://discord.com.verify-account.ru/login',
  'https://discord.gg.invite-join.xyz/abc',
  'https://discord-nitro.com/?utm_source=dm',
  '@everyone free nitro for 3 months https://discord-promo.site/claim',
  'I accidentally reported you, please verify here https://discord-support.net/appeal',
  // Steam
  'https://steamcommunlty.com/tradeoffer/new/?partner=1',
  'https://stearncommunity.com/id/giveaway',
  'https://steamcommunity.ru/gift/activation',
  'https://steam-giveaway.xyz/',
  'https://steamcomnunity.com/profiles/765',
  'https://steancommunity.com/id/x',
  'https://stemcommunity.com/tradeoffer',
  'https://store-steampowered.ru/app/730',
  'https://steampowered.com.ru/login',
  'https://steam-trade.link/offer',
  'https://steamcommunity.com-tradeoffer.xyz/new',
  'https://steamcommunіty.com/id/x',
  // Other brands
  'https://metamask-wallet-verify.com/',
  'https://phantom-airdrop.app/claim',
  'https://epicgames-free.com/vbucks',
  'https://epic-games.store/fortnite',
  'https://coinbase-support.help/case',
  'https://opensea-mint.xyz/',
  'https://metamask.io.wallet-connect.site/',
  'https://trustwallet-restore.com/',
  // Obfuscation and disguise
  'hxxps://dlscord[.]com/gift',
  'claim it here dlscord . gift/abc',
  'dlscord.gift/abc no scheme',
  'check this out <https://dlscord.com/verify>',
  '[discord.com/nitro](https://dlscord.gift/nitro)',
  'https://dis​cord-gift.com/claim',
  'https://discord.com@evil-login.ru/login',
  'verify your account at http://203.0.113.10/login',
];

export const LEGIT_MESSAGES: string[] = [
  'https://discord.com/channels/123/456',
  'join us https://discord.gg/abc',
  'https://discordapp.com/invite/abc',
  'https://cdn.discordapp.com/attachments/1/2/image.png',
  'https://media.discordapp.net/attachments/1/2/image.png',
  'https://discord.gift/AbCdEf123 enjoy!',
  'https://support.discord.com/hc/en-us',
  'https://discord.com/nitro free nitro trial on the official page',
  'https://github.com/discordjs/discord.js',
  'https://discordjs.guide/',
  'https://discord.js.org/docs',
  'https://top.gg/bot/123',
  'steam sale https://store.steampowered.com/app/730',
  'https://steamcommunity.com/id/foo',
  'https://steamdb.info/app/730/',
  'https://www.epicgames.com/store/en-US/',
  'https://www.roblox.com/games/1',
  'https://metamask.io/download/',
  'https://opensea.io/collection/x',
  'https://www.coinbase.com/',
  'https://phantom.app/',
  'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  'https://youtu.be/dQw4w9WgXcQ',
  'https://en.wikipedia.org/wiki/Discord',
  'https://www.reddit.com/r/discordapp/',
  'https://twitter.com/discord',
  'https://x.com/steam',
  'https://www.twitch.tv/someone',
  'https://tenor.com/view/cat-123',
  'https://imgur.com/a/abc',
  'https://open.spotify.com/track/abc',
  'https://stackoverflow.com/q/1',
  'https://www.npmjs.com/package/discord.js',
  'https://docs.python.org/3/',
  'https://www.google.com/search?q=discord+nitro',
  'https://news.ycombinator.com/',
  'https://www.bbc.co.uk/news',
  'https://www.amazon.co.uk/dp/B000',
  'https://example.com/',
  'https://medium.com/@user/post',
  'https://streamlabs.com/',
  'https://www.livestream.com/',
  'https://www.discogs.com/',
  'https://www.discover.com/',
  'https://discourse.org/',
  'https://teamspeak.com/',
  'https://store.playstation.com/',
  'https://www.xbox.com/',
  'https://www.minecraft.net/',
  'https://www.curseforge.com/',
  'https://www.nexusmods.com/',
  'https://www.paypal.com/',
  'https://ko-fi.com/someone',
  'https://www.discordtips.com/',
  'https://blog.steampunk.com/',
  'https://gaming.info/news',
  'https://example.xyz/',
  'dev server is at http://127.0.0.1:3000',
  'http://localhost:3000/api',
  'my email is someone@example.com',
  'I love node.js and my notes are in file.txt',
  'meet at 5.30, version 1.2.3 is out',
  'free nitro giveaway tonight in #events',
];
